Part_A_Variant_1: Part_A_Variant_1.c
	gcc Part_A_Variant_1.c -o Part_A_Variant_1 -lpthread

Part_A_Variant_2: Part_A_Variant_2.c
	gcc Part_A_Variant_2.c -o Part_A_Variant_2 -lpthread

Part_B_Variant_1: Part_B_Variant_1.c
	gcc Part_B_Variant_1.c -o Part_B_Variant_1 -lpthread

Part_B_Variant_2: Part_B_Variant_2.c
	gcc Part_B_Variant_2.c -o Part_B_Variant_2 -lpthread

Part_A_Variant_1_run:
	./Part_A_Variant_1

Part_A_Variant_2_run:
	./Part_A_Variant_2

Part_B_Variant_1_run:
	./Part_B_Variant_1

Part_B_Variant_2_run:
	./Part_B_Variant_2

clean:
	rm -v Part_A_Variant_1 Part_A_Variant_2 Part_B_Variant_1 Part_B_Variant_2